### 모든 연락처 조회
GET http://localhost:8080/accounts/

### 연락처 추가
POST http://localhost:8080/account
Content-Type: application/json

< ./add.json

### 연락처 업데이트
PUT http://localhost:8080/account/1
Content-Type: application/json

< ./add.json